version: "3.9"

services:
  server:
    build:
      context: .
    container_name: todolist
    ports:
      - '8080:8080'
    depends_on:
      db:
        condition: service_healthy

  db:
    image: mysql:8
    container_name: todolist_db
    environment:
      MYSQL_ROOT_PASSWORD: 'professional1'
    ports:
      - '3308:3306'
    volumes:
      - my_todolist_db:/var/lib/mysql
    healthcheck:
      test: "/usr/bin/mysql --user=root --password=professional1 --execute \"SHOW DATABASES;\""
      interval: 3s
      timeout: 30s
      retries: 10

volumes:
  my_todolist_db: